/** Bundled viewer shared by web, desktop and native WebView; credentials arrive only in the fragment. */
export const gameViewerDocument = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Unity game</title><style>
:root{color-scheme:dark;font-family:system-ui;background:#14181e;color:#e7ecf2}body{margin:0;padding:12px}button,input,select{font:inherit;color:inherit;background:#252d38;border:1px solid #546174;border-radius:6px;padding:8px}button{cursor:pointer}button:disabled{opacity:.45;cursor:default}header,.controls,.setup{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.setup input{flex:1;min-width:180px}#status{min-height:1.5em;font-size:13px;color:#acbbcc}#game{display:block;width:100%;max-height:65vh;object-fit:contain;background:#050607;touch-action:none;outline-offset:2px}#surface{position:relative;margin:12px 0}#pad{display:flex;gap:10px;margin:12px 0}#pad button{touch-action:none;min-width:65px;min-height:50px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:7px;border-bottom:1px solid #384353}td input{width:90px}svg{width:150px;height:40px}#report{width:100%;height:600px;border:0}label{display:flex;align-items:center;gap:6px}#monitorStatus{font-size:13px;color:#acbbcc}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:550px){svg{width:75px}td input{width:65px}}
</style></head><body><h2>Unity game</h2><div class="setup"><label>Target<select id="kind"><option value="editor">Editor</option><option value="player">Player</option></select></label><label class="sr" for="path">Project path or player port file</label><input id="path" placeholder="Unity project path"><button id="open">Connect</button><button id="close" disabled>Disconnect</button></div><p id="status" role="status">Connecting to T3…</p><header><button id="take" disabled>Take control</button><button id="release" disabled>Release</button><span id="owner">Viewing only</span></header><div id="surface"><img id="game" alt="Live Unity game" tabindex="0"></div><div id="pad" aria-label="Touch controls"><button data-key="LeftArrow">← Left</button><button data-key="RightArrow">Right →</button><button data-key="Space">Jump</button></div><div class="controls"><button id="monitor" disabled>Monitor 60 seconds</button><button id="stop" disabled>Stop monitor</button><button id="export" disabled>Save report</button></div><p id="monitorStatus">Choose variables to monitor. Histories retain up to 256 samples.</p><table><thead><tr><th>Watch</th><th>Variable</th><th>Value / edit</th><th>History</th></tr></thead><tbody id="variables"></tbody></table><iframe id="report" title="Gameplay observation report" sandbox="" hidden></iframe><script>
(()=>{
const $=id=>document.getElementById(id);const credential=new URLSearchParams(location.hash.slice(1)).get('ticket')||'';history.replaceState(null,'',location.pathname);
let session=null,catalog=null,lease=null,sequence=0,keys=new Set(),point={x:.5,y:.5},button=false,disposed=false,hidden=false,frameUrl=null,frameError=null,reportUrl=null,cursor=0,watchId=null,samples=[],canOperate=false,inputBusy=false,frameTimer,stateTimer,heartbeat,revision=0;
const rows=new Map();
function status(message){$('status').textContent=message;}
async function http(path,body){const response=await fetch(new URL(path,location.href),{method:body?'POST':'GET',headers:{'x-t3-game-ticket':credential,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(7000)});if(!response.ok){const err=await response.json().catch(()=>({message:'Connection lost'}));throw Error(err.message||'Game request failed');}return response;}
async function command(action,fields={}){return(await http('command',{action,sessionId:session,...fields})).json();}
function controlling(value){lease=value;keys.clear();button=false;$('release').disabled=!lease;$('take').disabled=!session||!canOperate;$('monitor').disabled=!lease;$('stop').disabled=!lease;$('owner').textContent=lease?'You control input':'Viewing only';}
async function release(){const previous=lease;controlling(null);if(previous&&session)await command('release',{lease:previous}).catch(()=>{});}
async function input(){if(!lease||!session||hidden||inputBusy)return;inputBusy=true;const current=lease;try{await command('input',{lease:current,sequence:++sequence,keys:[...keys],...point,button,durationMs:500});}catch(error){if(lease===current)controlling(null);status(error.message);}finally{inputBusy=false;}}
function updateRows(){for(const hook of catalog.hooks){const row=rows.get(hook.handle);const selected=samples.filter(s=>hook.handle in s.values);const last=selected.at(-1)?.values[hook.handle];row.output.textContent=last===undefined?'—':String(last);row.write.disabled=!lease||last===undefined;row.previous=last;const numeric=selected.filter(s=>typeof s.values[hook.handle]==='number');if(numeric.length){const values=numeric.map(s=>s.values[hook.handle]);const min=Math.min(...values),range=Math.max(.0001,Math.max(...values)-min),start=numeric[0].sampledAtMs,span=Math.max(1,numeric.at(-1).sampledAtMs-start);row.line.setAttribute('points',numeric.map(s=>((s.sampledAtMs-start)/span*150)+','+(38-(s.values[hook.handle]-min)/range*35)).join(' '));}}}
function makeRows(){rows.clear();$('variables').replaceChildren();for(const hook of catalog.hooks){const tr=document.createElement('tr'),choose=document.createElement('input');choose.type='checkbox';choose.checked=rows.size<8;choose.setAttribute('aria-label','Monitor '+hook.key);const key=document.createElement('th');key.textContent=hook.key;key.title=hook.description;const check=document.createElement('td');check.append(choose);const cell=document.createElement('td'),output=document.createElement('span');output.textContent='—';cell.append(output);const edit=document.createElement('input'),write=document.createElement('button');write.textContent='Set';write.disabled=true;edit.setAttribute('aria-label','Set '+hook.key);if(hook.writable){cell.append(document.createElement('br'),edit,write);}const chart=document.createElement('td'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),line=document.createElementNS(svg.namespaceURI,'polyline');svg.setAttribute('viewBox','0 0 150 40');line.setAttribute('fill','none');line.setAttribute('stroke','#91ceff');line.setAttribute('stroke-width','2');svg.append(line);chart.append(svg);tr.append(check,key,cell,chart);$('variables').append(tr);const row={choose,output,edit,write,line,previous:undefined};rows.set(hook.handle,row);write.onclick=async()=>{try{const value=hook.type==='string'?edit.value:JSON.parse(edit.value);await command('write',{lease,handle:hook.handle,value,expected:row.previous});status('Updated '+hook.key);}catch(error){status(error.message);}};}}
async function pumpFrames(version){if(disposed||version!==revision||!session)return;if(hidden){frameTimer=setTimeout(()=>pumpFrames(version),500);return;}try{const response=await http('frame/'+encodeURIComponent(session));const blob=await response.blob();if(version!==revision)return;const next=URL.createObjectURL(blob);const old=frameUrl;frameUrl=next;$('game').src=next;if(frameError&&$('status').textContent===frameError)status('Live game connected');frameError=null;if(old)URL.revokeObjectURL(old);}catch(error){frameError=error.message;status(frameError);}finally{if(version===revision)frameTimer=setTimeout(()=>pumpFrames(version),100);}}
async function states(version){if(disposed||version!==revision||!session)return;try{const state=await command('state',{afterSequence:cursor});if(version!==revision)return;if(state.generation!==catalog.generation)throw Error('Unity reloaded; reconnect.');const watch=state.monitor;if(watch){if(watchId!==watch.id){samples=[];cursor=0;watchId=watch.id;}samples.push(...watch.samples);samples=samples.slice(-256);cursor=Math.max(cursor,...watch.samples.map(s=>s.sequence));$('monitorStatus').textContent='Monitor '+watch.status+' · '+samples.length+' retained · '+watch.dropped+' dropped'+(watch.error?' · '+watch.error:'');updateRows();}if(!lease)$('owner').textContent=state.controller.role?state.controller.role+' has control':'Viewing only';}catch(error){status(error.message);}finally{if(version===revision)stateTimer=setTimeout(()=>states(version),hidden?2000:500);}}
async function disconnect(){revision++;clearTimeout(frameTimer);clearTimeout(stateTimer);await release();const old=session;session=null;if(old)await command('close',{sessionId:old}).catch(()=>{});$('close').disabled=true;$('take').disabled=true;$('export').disabled=true;$('game').removeAttribute('src');if(frameUrl){URL.revokeObjectURL(frameUrl);frameUrl=null;}status('Disconnected');}
$('open').onclick=async()=>{try{await disconnect();const kind=$('kind').value,path=$('path').value;const result=await command('open',{target:kind==='editor'?{kind,projectPath:path}:{kind,portFile:path}});session=result.sessionId;catalog=result.catalog;cursor=0;samples=[];makeRows();$('close').disabled=false;$('take').disabled=!canOperate;$('export').disabled=false;status('Connected · click Take control to play');const version=++revision;pumpFrames(version);states(version);}catch(error){status(error.message);}};
$('close').onclick=disconnect;$('take').onclick=async()=>{try{const result=await command('acquire',{takeover:true});if(lease!==result.lease)sequence=0;controlling(result.lease);$('game').focus();status('Control acquired. Arrow keys move; Space jumps.');}catch(error){status(error.message);}};$('release').onclick=release;
$('monitor').onclick=async()=>{try{const handles=[...rows].filter(([,r])=>r.choose.checked).map(([h])=>h);const result=await command('monitor',{lease,handles,durationMs:60000});samples=result.samples;cursor=samples.at(-1)?.sequence||0;updateRows();}catch(error){status(error.message);}};
$('stop').onclick=()=>command('stop_monitor',{lease}).catch(error=>status(error.message));
$('export').onclick=async()=>{try{const report=await command('report');if(reportUrl)URL.revokeObjectURL(reportUrl);reportUrl=URL.createObjectURL(new Blob([report.html],{type:'text/html'}));$('report').src=reportUrl;$('report').hidden=false;status('Report snapshot saved.');}catch(error){status(error.message);}};
const keyNames={ArrowLeft:'LeftArrow',ArrowRight:'RightArrow',ArrowUp:'UpArrow',ArrowDown:'DownArrow',' ':'Space',w:'W',a:'A',s:'S',d:'D'};
$('game').onkeydown=e=>{const key=keyNames[e.key];if(lease&&key){e.preventDefault();keys.add(key);input();}};$('game').onkeyup=e=>{const key=keyNames[e.key];if(key){e.preventDefault();keys.delete(key);input();}};
function pointer(e){const r=$('game').getBoundingClientRect();const ratio=($('game').naturalWidth||r.width)/($('game').naturalHeight||r.height);const w=Math.min(r.width,r.height*ratio),h=w/ratio;point={x:Math.max(0,Math.min(1,(e.clientX-r.left-(r.width-w)/2)/w)),y:Math.max(0,Math.min(1,(e.clientY-r.top-(r.height-h)/2)/h))};}
$('game').onpointerdown=e=>{if(!lease)return;e.preventDefault();$('game').focus();$('game').setPointerCapture(e.pointerId);pointer(e);button=true;input();};$('game').onpointermove=e=>{if(lease){pointer(e);input();}};$('game').onpointerup=e=>{button=false;pointer(e);input();};$('game').onpointercancel=()=>{button=false;keys.clear();input();};
for(const el of document.querySelectorAll('[data-key]')){el.onpointerdown=e=>{if(!lease)return;e.preventDefault();el.setPointerCapture(e.pointerId);keys.add(el.dataset.key);input();};el.onpointerup=el.onpointercancel=()=>{keys.delete(el.dataset.key);input();};}
function suspend(){hidden=document.hidden;keys.clear();button=false;release();}document.addEventListener('visibilitychange',suspend);window.addEventListener('blur',release);window.addEventListener('pagehide',()=>{disposed=true;clearInterval(heartbeat);release();});
heartbeat=setInterval(input,200);
http('config').then(r=>r.json()).then(config=>{canOperate=config.canOperate;$('path').value=config.cwd;$('open').disabled=!canOperate;status('Choose an Editor project or Player port file.');}).catch(error=>status(error.message));
})();
</script></body></html>`;
